# Generated by Django 3.0.6 on 2020-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='film_images/')),
                ('description', models.TextField(max_length=512)),
                ('role', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('film_crew', models.TextField(max_length=512)),
            ],
        ),
    ]
