# Generated by Django 3.0.6 on 2020-05-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tele_images/')),
                ('description', models.TextField(max_length=522)),
                ('role', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
